### ISSUE TITLE
500 Internal Server Error when adding new build

### ISSUE THREAD

**Issue by slavashvets** [simpleci/simpleci#3]
### Steps to reproduce

1. Use local example to run `docker-compose up`
2. Login as admin/admin
3. Add new gitlab repo
4. Add new SSH key
5. Create new project
6. Press button `+ New build`

### Expected
"New build" form

### Actual
URL:
`http://.../project/1/build/create`

Message:
```
Oops! An Error Occurred

The server returned a "500 Internal Server Error".

Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.
```

### Log output from docker-compose
```
$ docker-compose.exe up
Starting simpleci_rabbitmq_1
Starting simpleci_redis_1
Starting simpleci_mysql_1
Starting simpleci_worker_1
Starting simpleci_dispatcher_1
Creating simpleci_frontend_1
Attaching to simpleci_rabbitmq_1, simpleci_mysql_1, simpleci_redis_1, simpleci_worker_1, simpleci_dispatcher_1, simpleci_frontend_1
mysql_1       | 2016-12-27 09:57:20 0 [Note] mysqld (mysqld 5.6.35) starting as process 1 ...
redis_1       | 1:C 27 Dec 09:57:20.360 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
mysql_1       | 2016-12-27 09:57:20 1 [Note] Plugin 'FEDERATED' is disabled.
worker_1      |  INFO [main] (TestServicesUtils.java:65) - rabbitmq: connecting to rabbitmq:5672, try 1
redis_1       |                 _._
mysql_1       | 2016-12-27 09:57:20 1 [Note] InnoDB: Using atomics to ref count buffer pool pages
redis_1       |            _.-``__ ''-._
worker_1      |  INFO [main] (ConnectionHandler.java:240) - Creating connection cxn-1 to [rabbitmq:5672]
mysql_1       | 2016-12-27 09:57:20 1 [Note] InnoDB: The InnoDB memory heap is disabled
redis_1       |       _.-``    `.  `_.  ''-._           Redis 3.2.6 (00000000/0) 64 bit
dispatcher_1  |  INFO [main] (TestServicesUtils.java:65) - rabbitmq: connecting to rabbitmq:5672, try 1
mysql_1       | 2016-12-27 09:57:20 1 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
redis_1       |   .-`` .-```.  ```\/    _.,_ ''-._
worker_1      | ERROR [main] (ConnectionHandler.java:130) - Failed to create connection cxn-1
mysql_1       | 2016-12-27 09:57:20 1 [Note] InnoDB: Memory barrier is not used
redis_1       |  (    '      ,       .-`  | `,    )     Running in standalone mode
dispatcher_1  |  INFO [main] (TestServicesUtils.java:71) - Failed to connect: rabbitmq
worker_1      | java.net.ConnectException: Connection refused (Connection refused)
mysql_1       | 2016-12-27 09:57:20 1 [Note] InnoDB: Compressed tables use zlib 1.2.8
redis_1       |  |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
worker_1      |         at java.net.PlainSocketImpl.socketConnect(Native Method)
mysql_1       | 2016-12-27 09:57:20 1 [Note] InnoDB: Using Linux native AIO
redis_1       |  |    `-._   `._    /     _.-'    |     PID: 1
worker_1      |         at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
redis_1       |   `-._    `-._  `-./  _.-'    _.-'
worker_1      |         at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
mysql_1       | 2016-12-27 09:57:20 1 [Note] InnoDB: Using CPU crc32 instructions
redis_1       |  |`-._`-._    `-.__.-'    _.-'_.-'|
worker_1      |         at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
redis_1       |  |    `-._`-._        _.-'_.-'    |           http://redis.io
mysql_1       | 2016-12-27 09:57:20 1 [Note] InnoDB: Initializing buffer pool, size = 128.0M
worker_1      |         at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
redis_1       |   `-._    `-._`-.__.-'_.-'    _.-'
worker_1      |         at java.net.Socket.connect(Socket.java:589)
redis_1       |  |`-._`-._    `-.__.-'    _.-'_.-'|
mysql_1       | 2016-12-27 09:57:20 1 [Note] InnoDB: Completed initialization of buffer pool
worker_1      |         at com.rabbitmq.client.impl.FrameHandlerFactory.create(FrameHandlerFactory.java:32)
redis_1       |  |    `-._`-._        _.-'_.-'    |
worker_1      |         at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:676)
mysql_1       | 2016-12-27 09:57:20 1 [Note] InnoDB: Highest supported file format is Barracuda.
redis_1       |   `-._    `-._`-.__.-'_.-'    _.-'
worker_1      |         at net.jodah.lyra.internal.ConnectionHandler$3.call(ConnectionHandler.java:244)
redis_1       |       `-._    `-.__.-'    _.-'
worker_1      |         at net.jodah.lyra.internal.ConnectionHandler$3.call(ConnectionHandler.java:237)
mysql_1       | 2016-12-27 09:57:20 1 [Note] InnoDB: 128 rollback segment(s) are active.
redis_1       |           `-._        _.-'
worker_1      |         at net.jodah.lyra.internal.RetryableResource.callWithRetries(RetryableResource.java:51)
redis_1       |               `-.__.-'
worker_1      |         at net.jodah.lyra.internal.ConnectionHandler.createConnection(ConnectionHandler.java:237)
redis_1       |
worker_1      |         at net.jodah.lyra.internal.ConnectionHandler.createConnection(ConnectionHandler.java:120)
mysql_1       | 2016-12-27 09:57:20 1 [Note] InnoDB: Waiting for purge to start
redis_1       | 1:M 27 Dec 09:57:20.362 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
worker_1      |         at net.jodah.lyra.Connections.create(Connections.java:69)
worker_1      |         at simpleci.shared.utils.ConnectionUtils.createRabbitmqConnection(ConnectionUtils.java:40)
mysql_1       | 2016-12-27 09:57:20 1 [Note] InnoDB: 5.6.35 started; log sequence number 2162025
redis_1       | 1:M 27 Dec 09:57:20.362 # Server started, Redis version 3.2.6
worker_1      |         at simpleci.shared.utils.TestServicesUtils.testRabbitmq(TestServicesUtils.java:66)
redis_1       | 1:M 27 Dec 09:57:20.362 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
worker_1      |         at Main.testServices(Main.java:47)
mysql_1       | 2016-12-27 09:57:20 1 [Note] Server hostname (bind-address): '*'; port: 3306
redis_1       | 1:M 27 Dec 09:57:20.362 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
worker_1      |         at Main.main(Main.java:26)
mysql_1       | 2016-12-27 09:57:20 1 [Note] IPv6 is available.
mysql_1       | 2016-12-27 09:57:20 1 [Note]   - '::' resolves to '::';
redis_1       | 1:M 27 Dec 09:57:20.362 * DB loaded from disk: 0.000 seconds
worker_1      |  INFO [main] (TestServicesUtils.java:71) - Failed to connect: Connection refused (Connection refused)
redis_1       | 1:M 27 Dec 09:57:20.362 * The server is now ready to accept connections on port 6379
mysql_1       | 2016-12-27 09:57:20 1 [Note] Server socket created on IP: '::'.
mysql_1       | 2016-12-27 09:57:20 1 [Warning] 'proxies_priv' entry '@ root@2ff84aec5544' ignored in --skip-name-resolve mode.
mysql_1       | 2016-12-27 09:57:20 1 [Note] Event Scheduler: Loaded 0 events
mysql_1       | 2016-12-27 09:57:20 1 [Note] mysqld: ready for connections.
mysql_1       | Version: '5.6.35'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
frontend_1    | Setup configuration
frontend_1    | Initializing log dirs
rabbitmq_1    |
rabbitmq_1    | =INFO REPORT==== 27-Dec-2016::09:57:22 ===
rabbitmq_1    | Starting RabbitMQ 3.6.6 on Erlang 19.0
rabbitmq_1    | Copyright (C) 2007-2016 Pivotal Software, Inc.
rabbitmq_1    | Licensed under the MPL.  See http://www.rabbitmq.com/
rabbitmq_1    |
rabbitmq_1    |               RabbitMQ 3.6.6. Copyright (C) 2007-2016 Pivotal Software, Inc.
rabbitmq_1    |   ##  ##      Licensed under the MPL.  See http://www.rabbitmq.com/
rabbitmq_1    |   ##  ##
rabbitmq_1    |   ##########  Logs: tty
rabbitmq_1    |   ######  ##        tty
rabbitmq_1    |   ##########
rabbitmq_1    |               Starting broker...
rabbitmq_1    |
rabbitmq_1    | =INFO REPORT==== 27-Dec-2016::09:57:22 ===
rabbitmq_1    | node           : rabbit@a97906c3b6b9
rabbitmq_1    | home dir       : /var/lib/rabbitmq
rabbitmq_1    | config file(s) : /etc/rabbitmq/rabbitmq.config
rabbitmq_1    | cookie hash    : 7llyk541G3kDXkeffIokQw==
rabbitmq_1    | log            : tty
rabbitmq_1    | sasl log       : tty
rabbitmq_1    | database dir   : /var/lib/rabbitmq/mnesia/rabbit@a97906c3b6b9
worker_1      |  INFO [main] (TestServicesUtils.java:65) - rabbitmq: connecting to rabbitmq:5672, try 2
worker_1      |  INFO [main] (ConnectionHandler.java:240) - Creating connection cxn-2 to [rabbitmq:5672]
worker_1      | ERROR [main] (ConnectionHandler.java:130) - Failed to create connection cxn-2
worker_1      | java.net.ConnectException: Connection refused (Connection refused)
worker_1      |         at java.net.PlainSocketImpl.socketConnect(Native Method)
worker_1      |         at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
worker_1      |         at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
worker_1      |         at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
worker_1      |         at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
worker_1      |         at java.net.Socket.connect(Socket.java:589)
worker_1      |         at com.rabbitmq.client.impl.FrameHandlerFactory.create(FrameHandlerFactory.java:32)
worker_1      |         at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:676)
worker_1      |         at net.jodah.lyra.internal.ConnectionHandler$3.call(ConnectionHandler.java:244)
worker_1      |         at net.jodah.lyra.internal.ConnectionHandler$3.call(ConnectionHandler.java:237)
worker_1      |         at net.jodah.lyra.internal.RetryableResource.callWithRetries(RetryableResource.java:51)
worker_1      |         at net.jodah.lyra.internal.ConnectionHandler.createConnection(ConnectionHandler.java:237)
worker_1      |         at net.jodah.lyra.internal.ConnectionHandler.createConnection(ConnectionHandler.java:120)
worker_1      |         at net.jodah.lyra.Connections.create(Connections.java:69)
worker_1      |         at simpleci.shared.utils.ConnectionUtils.createRabbitmqConnection(ConnectionUtils.java:40)
worker_1      |         at simpleci.shared.utils.TestServicesUtils.testRabbitmq(TestServicesUtils.java:66)
worker_1      |         at Main.testServices(Main.java:47)
worker_1      |         at Main.main(Main.java:26)
worker_1      |  INFO [main] (TestServicesUtils.java:71) - Failed to connect: Connection refused (Connection refused)
dispatcher_1  |  INFO [main] (TestServicesUtils.java:65) - rabbitmq: connecting to rabbitmq:5672, try 2
dispatcher_1  |  INFO [main] (TestServicesUtils.java:71) - Failed to connect: rabbitmq
rabbitmq_1    |
rabbitmq_1    | =INFO REPORT==== 27-Dec-2016::09:57:22 ===
rabbitmq_1    | Memory limit set to 25768MB of 64421MB total.
rabbitmq_1    |
rabbitmq_1    | =INFO REPORT==== 27-Dec-2016::09:57:22 ===
rabbitmq_1    | Disk free limit set to 50MB
rabbitmq_1    |
rabbitmq_1    | =INFO REPORT==== 27-Dec-2016::09:57:22 ===
rabbitmq_1    | Limiting to approx 65436 file handles (58890 sockets)
rabbitmq_1    |
rabbitmq_1    | =INFO REPORT==== 27-Dec-2016::09:57:22 ===
rabbitmq_1    | FHC read buffering:  OFF
rabbitmq_1    | FHC write buffering: ON
rabbitmq_1    |
rabbitmq_1    | =INFO REPORT==== 27-Dec-2016::09:57:22 ===
rabbitmq_1    | Priority queues enabled, real BQ is rabbit_variable_queue
rabbitmq_1    |
rabbitmq_1    | =INFO REPORT==== 27-Dec-2016::09:57:22 ===
rabbitmq_1    | Starting rabbit_node_monitor
rabbitmq_1    |
rabbitmq_1    | =INFO REPORT==== 27-Dec-2016::09:57:22 ===
rabbitmq_1    | msg_store_transient: using rabbit_msg_store_ets_index to provide index
rabbitmq_1    |
rabbitmq_1    | =INFO REPORT==== 27-Dec-2016::09:57:22 ===
rabbitmq_1    | msg_store_persistent: using rabbit_msg_store_ets_index to provide index
rabbitmq_1    |
rabbitmq_1    | =WARNING REPORT==== 27-Dec-2016::09:57:22 ===
rabbitmq_1    | msg_store_persistent: rebuilding indices from scratch
rabbitmq_1    |
rabbitmq_1    | =INFO REPORT==== 27-Dec-2016::09:57:22 ===
rabbitmq_1    | started TCP Listener on [::]:5672
rabbitmq_1    |  completed with 0 plugins.
rabbitmq_1    |
rabbitmq_1    | =INFO REPORT==== 27-Dec-2016::09:57:22 ===
rabbitmq_1    | Server startup complete; 0 plugins started.
frontend_1    |
frontend_1    |  // Clearing the cache for the prod environment with debug
frontend_1    |  // false
frontend_1    |
worker_1      |  INFO [main] (TestServicesUtils.java:65) - rabbitmq: connecting to rabbitmq:5672, try 3
worker_1      |  INFO [main] (ConnectionHandler.java:240) - Creating connection cxn-3 to [rabbitmq:5672]
dispatcher_1  |  INFO [main] (TestServicesUtils.java:65) - rabbitmq: connecting to rabbitmq:5672, try 3
dispatcher_1  |  INFO [main] (TestServicesUtils.java:71) - Failed to connect: rabbitmq
rabbitmq_1    |
rabbitmq_1    | =INFO REPORT==== 27-Dec-2016::09:57:23 ===
rabbitmq_1    | accepting AMQP connection <0.286.0> (172.17.0.8:39236 -> 172.17.0.5:5672)
worker_1      |  INFO [main] (ConnectionHandler.java:249) - Created connection cxn-3 to amqp://172.17.0.5:5672/
worker_1      |  INFO [main] (TestServicesUtils.java:68) - Connection to rabbitmq established successfully
rabbitmq_1    |
rabbitmq_1    | =INFO REPORT==== 27-Dec-2016::09:57:23 ===
rabbitmq_1    | closing AMQP connection <0.286.0> (172.17.0.8:39236 -> 172.17.0.5:5672)
worker_1      |  INFO [main] (ConnectionHandler.java:240) - Creating connection cxn-4 to [rabbitmq:5672]
rabbitmq_1    |
rabbitmq_1    | =INFO REPORT==== 27-Dec-2016::09:57:23 ===
rabbitmq_1    | accepting AMQP connection <0.295.0> (172.17.0.8:39240 -> 172.17.0.5:5672)
worker_1      |  INFO [main] (ConnectionHandler.java:249) - Created connection cxn-4 to amqp://172.17.0.5:5672/
worker_1      |  INFO [main] (ConnectionHandler.java:160) - Created channel-1 on cxn-4
worker_1      |  INFO [main] (Main.java:31) - Started worker cbc6e09f-58f4-4c8f-aa92-fe3d47ce75e4
worker_1      |  INFO [main] (Main.java:32) - Worker parameters: AppParameters{worker_id=cbc6e09f-58f4-4c8f-aa92-fe3d47ce75e4, worker_type=local, worker_options=simpleci.shared.worker.options.LocalWorkerOptions@6ec8211c, rabbitmq_host=rabbitmq, rabbitmq_port=rabbitmq, rabbitmq_user=guest, rabbitmq_password=guest, exit_if_inactive=false, minimum_running_time=570, time_granularity=60}
worker_1      |  INFO [main] (ConnectionHandler.java:160) - Created channel-2 on cxn-4
worker_1      |  INFO [main] (ChannelHandler.java:272) - Created consumer-amq.ctag-sK1qF8D7wEgMT9guR6Dq4A of amq.gen-TpJrQFvILYIbPBfEHVy5qw via channel-2 on cxn-4
worker_1      |  INFO [Thread-2] (ConnectionHandler.java:160) - Created channel-3 on cxn-4
worker_1      |  INFO [Thread-2] (ChannelHandler.java:272) - Created consumer-amq.ctag-DbMXxox2w_VADzlGRZhE2w of local via channel-3 on cxn-4
worker_1      |  INFO [Thread-2] (JobConsumer.java:43) - Listen on queue local
dispatcher_1  |  INFO [main] (TestServicesUtils.java:65) - rabbitmq: connecting to rabbitmq:5672, try 4
dispatcher_1  |  INFO [main] (TestServicesUtils.java:71) - Failed to connect: rabbitmq
dispatcher_1  |  INFO [main] (TestServicesUtils.java:65) - rabbitmq: connecting to rabbitmq:5672, try 5
dispatcher_1  |  INFO [main] (TestServicesUtils.java:71) - Failed to connect: rabbitmq
frontend_1    |  [OK] Cache for the "prod" environment (debug=false) was successfully cleared.
frontend_1    |
frontend_1    | Waiting for mysql: mysql:3306 simpleci:simpleci
frontend_1    |
frontend_1    | Waiting for redis: redis:6379
frontend_1    |
frontend_1    | mysql: [Warning] Using a password on the command line interface can be insecure.
frontend_1    | Install database migrations
frontend_1    |
frontend_1    |                     Application Migrations
frontend_1    |
frontend_1    |
frontend_1    | No migrations to execute.
frontend_1    | 2016-12-27 09:57:26,063 CRIT Supervisor running as root (no user in config file)
frontend_1    | 2016-12-27 09:57:26,079 INFO RPC interface 'supervisor' initialized
frontend_1    | 2016-12-27 09:57:26,079 CRIT Server 'unix_http_server' running without any HTTP authentication checking
frontend_1    | 2016-12-27 09:57:26,079 INFO supervisord started with pid 1
dispatcher_1  |  INFO [main] (TestServicesUtils.java:65) - rabbitmq: connecting to rabbitmq:5672, try 6
dispatcher_1  |  INFO [main] (TestServicesUtils.java:71) - Failed to connect: rabbitmq
frontend_1    | 2016-12-27 09:57:27,082 INFO spawned: 'nginx' with pid 107
frontend_1    | 2016-12-27 09:57:27,083 INFO spawned: 'centrifugo' with pid 108
frontend_1    | 2016-12-27 09:57:27,084 INFO spawned: 'php7-fpm' with pid 109
dispatcher_1  |  INFO [main] (TestServicesUtils.java:65) - rabbitmq: connecting to rabbitmq:5672, try 7
dispatcher_1  |  INFO [main] (TestServicesUtils.java:71) - Failed to connect: rabbitmq
frontend_1    | 2016-12-27 09:57:28,185 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
frontend_1    | 2016-12-27 09:57:28,185 INFO success: centrifugo entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
frontend_1    | 2016-12-27 09:57:28,185 INFO success: php7-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
dispatcher_1  |  INFO [main] (TestServicesUtils.java:65) - rabbitmq: connecting to rabbitmq:5672, try 8
dispatcher_1  |  INFO [main] (TestServicesUtils.java:71) - Failed to connect: rabbitmq
dispatcher_1  |  INFO [main] (TestServicesUtils.java:65) - rabbitmq: connecting to rabbitmq:5672, try 9
dispatcher_1  |  INFO [main] (TestServicesUtils.java:71) - Failed to connect: rabbitmq
dispatcher_1  |  INFO [main] (TestServicesUtils.java:65) - rabbitmq: connecting to rabbitmq:5672, try 10
dispatcher_1  |  INFO [main] (TestServicesUtils.java:71) - Failed to connect: rabbitmq
dispatcher_1  |  INFO [main] (TestServicesUtils.java:79) - Failed connect to rabbitmq on rabbitmq:5672
```

**Comment by lewbor** [comment]
Fixed - problem was in docker-compose config - it must be link to rabbitmq in dispatcher and frontend

**Comment by slavashvets** [comment]
Thanks, but the error still appears.

The log files look better, except one place:
```
worker_1      |  INFO [main] (ConnectionHandler.java:240) - Creating connection cxn-1 to [rabbitmq:5672]
dispatcher_1  |  INFO [main] (TestServicesUtils.java:71) - Failed to connect: Connection refused (Connection refused)
worker_1      | ERROR [main] (ConnectionHandler.java:130) - Failed to create connection cxn-1
worker_1      | java.net.ConnectException: Connection refused (Connection refused)
worker_1      |         at java.net.PlainSocketImpl.socketConnect(Native Method)
worker_1      |         at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
worker_1      |         at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
worker_1      |         at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
worker_1      |         at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
worker_1      |         at java.net.Socket.connect(Socket.java:589)
worker_1      |         at com.rabbitmq.client.impl.FrameHandlerFactory.create(FrameHandlerFactory.java:32)
worker_1      |         at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:676)
worker_1      |         at net.jodah.lyra.internal.ConnectionHandler$3.call(ConnectionHandler.java:244)
worker_1      |         at net.jodah.lyra.internal.ConnectionHandler$3.call(ConnectionHandler.java:237)
worker_1      |         at net.jodah.lyra.internal.RetryableResource.callWithRetries(RetryableResource.java:51)
worker_1      |         at net.jodah.lyra.internal.ConnectionHandler.createConnection(ConnectionHandler.java:237)
worker_1      |         at net.jodah.lyra.internal.ConnectionHandler.createConnection(ConnectionHandler.java:120)
worker_1      |         at net.jodah.lyra.Connections.create(Connections.java:69)
worker_1      |         at simpleci.shared.utils.ConnectionUtils.createRabbitmqConnection(ConnectionUtils.java:40)
worker_1      |         at simpleci.shared.utils.TestServicesUtils.testRabbitmq(TestServicesUtils.java:66)
worker_1      |         at Main.testServices(Main.java:47)
worker_1      |         at Main.main(Main.java:26)
worker_1      |  INFO [main] (TestServicesUtils.java:71) - Failed to connect: Connection refused (Connection refused)
```

My `docker-compose.yml`
```
mysql:
  image: mysql:5.6
  env_file: parameters.env
  volumes:
    - "simpleci-mysql:/var/lib/mysql"
  volume_driver: convoy

rabbitmq:
  image: rabbitmq:latest
  volumes:
    - "simpleci-rabbitmq:/var/lib/rabbitmq"
  volume_driver: convoy

redis:
  image: redis:latest
  volumes:
    - "simpleci-redis:/var/lib/redis"
  volume_driver: convoy

dispatcher:
  image: simpleci/dispatcher
  links:
    - mysql:mysql
    - rabbitmq:rabbitmq
    - redis:redis
  env_file: parameters.env

worker:
  image: simpleci/worker
  links:
    - rabbitmq:rabbitmq
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
  env_file: parameters.env

frontend:
  image: simpleci/frontend
  links:
    - mysql:mysql
    - rabbitmq:rabbitmq
    - redis:redis
  ports:
    - "10002:80"
  volumes:
    - "simpleci-frontend:/var/log/simpleci"
  volume_driver: convoy
  env_file: parameters.env
```

**Comment by lewbor** [comment]
Tested your confuguration with my gitlab server - work well.. Can you show /var/www/var/logs/prod.log from frontend container?

**Comment by slavashvets** [comment]
Sure:
```
[2016-12-28 06:23:05] request.INFO: Matched route "build_create". {"route":"build_create","route_parameters":{"_controller":"controller.build:createAction","id":"1","_route":"build_create"},"request_uri":"http://***/project/1/build/create","method":"GET"} []
[2016-12-28 06:23:05] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2016-12-28 06:23:05] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"FOS\\UserBundle\\Security\\UserProvider"} []
[2016-12-28 06:23:07] request.CRITICAL: Uncaught PHP Exception Gitlab\Exception\RuntimeException: "{"message"=>"500 Internal Server Error"}" at /var/www/vendor/m4tthumphrey/php-gitlab-api/lib/Gitlab/HttpClient/Listener/ErrorListener.php line 60 {"exception":"[object] (Gitlab\\Exception\\RuntimeException(code: 500): {\"message\"=>\"500 Internal Server Error\"} at /var/www/vendor/m4tthumphrey/php-gitlab-api/lib/Gitlab/HttpClient/Listener/ErrorListener.php:60)"} []
[2016-12-28 06:23:07] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
```

**Comment by lewbor** [comment]
It seems that problem is in communicating between simpleci and gitlab. What version of gitlab are you using?

**Comment by slavashvets** [comment]
GitLab 7.1.1 facfec4

Could it be more descriptive message then "500 Error"? Or, at least, add requirement for minimal version of gitlab to the documentation?

**Comment by lewbor** [comment]
Fixed in 0.6.3 - now you can fill branch and commit info to build form even if an error with gitlab api occurred.
